project:
  type: website

website:
  title: "Gerard Chung"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: research.qmd
      - href: projects.qmd
#      - href: talks.qmd
  google-analytics: "G-T5QN0FBP69"
  favicon: favicon-32x32.png

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

