---
title: "Failure Resume"
---

Despite hearing and reading about the acceptance of failure and the prevalence of imposter syndrome, it's uncommon to witness the reality behind carefully curated CVs and social media posts. In an effort to promote a more genuine perspective, I have compiled a "failure" resume, showcasing aspects of my career-related rejections and setbacks. I believe that acknowledging these supposed failures is essential for personal growth and development. This list started in Aug 2023 and will be updated with more setbacks/failures.

I want to be clear that I am **not** putting them here to express my grievances. My only goal is to normalize setbacks and rejections. If you also experience any setbacks, I know you will find a way to cope with these setbacks. For me, my comfort comes from the this verse in the bible: "Blessed be the Lord, who daily bears our burden, The God who is our salvation. Selah" Psalms 68:19

**Journal paper rejected, June 2023\
**A revised paper was rejected even though it had excellent reviews because editor could not get a reviewer for the second review stage. We tried contacting the editor to appeal but she did not reply us our multiple emails. Eventually, we had to resubmit to a new journal and restart the review process. A whole 2 years of work down the drain.

**During doctoral degree training years, 2017 - 2021\
**I had many rejections from conferences, journals, grants. I had a paper that was rejected at least 4 times.

**Did not successfully get Tan Kah Kee Scholarship (i think in 2018)\
**I did terribly in the interview. I would not even award it to myself haha.

**Wrote papers/analyzed data for a tenure-track professor who promised to help publish them\
**It did not happen. Later on, I found out that something similar was published. I believe no credit was given to me.\
\
**Undergraduate academic performance, 2007**I did not graduate with a good academic performance from National University of Singapore. It was not 2nd-lower honors or even a merit.

# 
