---
title: "Projects"
---

## Practice Research with Social Service Agencies.

-   **Data Management and Curation: Best Practices**. I worked with an SSA to establish "good-enough" practices in data management and curation.

-   **Adoption Home Study Reports**. I analyzed the assessment reports to understand the assessment processes involved in determining the suitability of prospective adoptive parents.

## Text-as-data projects

-   **Parents' Corporal Punishment in Singapore Reddit Threads**. I am analyzing the positional stances of Reddit Singapore posters from a corpus of about 1000 posts.

-   **He killed himself: Dealing with grief from traumatic loss**. I am looking at themes of grief among survivors of suicide victimes from a large of text from Reddit threads.

-   **News Media Representations of Social Service Agencies During COVID-19 in Singapore**. Analysis of 1,095 news articles in Singapore on SSAs using a corpus linguistic approach. [\[Website\]](https://gerardchung.github.io/ssanews/)[\[Github\]](https://github.com/gerardchung/ssa_covid_news)\[[Article](https://fass.nus.edu.sg/ssr/wp-content/uploads/sites/8/2022/03/Snippet_Issue-1_2022_MinorityStress_CommunityConnectedness_NewsMedia_SocialServices.pdf)\]

-   **Text-mining news on Social Work Profession in Singapore**. Text data analysis of 7000 news articles related to Social Work Profession in Singapore. [\[Github\]](https://github.com/gerardchung/social_work_news_singapore)

-   **Annual reports of Social Service Agencies in Singapore**. Narratives of Directors' messages from 2017 to 2021. Project website coming up soon!

## Meta-analysis

-   **Parenting stress and children behavioral problems during COVID-19 pandemic**. We investigated the effects of parenting stress on child and parenting outcomes during the COVID-19 pandemic from 40 studies. [\[Website\]](https://gerardchung.github.io/meta_analysis_parentingstress/) \[[Preprint](https://psyarxiv.com/pzk5v/)\]

## Parenting / fathers

-   **Parenting During COVID-19 Circuit Breaker.** A survey study conducted with parents in Singapore during partial lock-down Circuit-breaker. [\[Website\]](https://sgcovidparenting.mystrikingly.com/)

-   **Parenting Books on Amazon.sg: Webscrapping titles** I analyzed titles of parenting books listed on Amazon.sg.[\[Website\]](https://gerardchung.github.io/amazon_parentingbooks/)

-   **Exploring the Role of Fathers in Singapore During the First 6 Years of their Child's Development.** A FGD study with fathers in collaboration with CHILD and SICS.

## Other projects

-   **In-Work Poverty and the Challenges of Getting By Among the Young**. Funded by the Social Science Thematic Research Grant, this project seeks to gain new insights on the kinds of "in-work" poverty that the working class are experiencing. It will focus on the challenges faced by lowly educated young workers (aged between 21 and 40) and their efforts at advancement. [\[website\]](https://fass.nus.edu.sg/ssr/research-projects/in-work-poverty-challenges-getting-by-among-the-young/)

-   **GUSTO: Growing Up in Singapore towards Healthy Outcomes.** GUSTO is Singapore's largest and most comprehensive birth cohort study. GUSTO is an important nation-wide medical study that gathers data from parents and their babies, starting from pregnancy.[\[Website\]](https://www.gusto.sg/)

-   **North Carolina State Administrative Data.** Collaboration with Associate Professor Paul Lanier at UNC School of Social Work. To build predictive risk models with administrative linked data for children in welfare.

-   **DADS CAN!** Collaboration with A\*STAR team to look at fathers and families. [Website](https://yahruj.wixsite.com/yahru)
