---
title: "Research"
---

# In Review

**Gerard Chung**, Jacqueline Lee Tilley, Nicholas Netto, Aloysius Chan, Paul Lanier. **Parenting Stress and its Impact on Parental and Child Functioning During the COVID-19 Pandemic: A Systematic Review and Meta-analysis**. [[Preprint]](https://psyarxiv.com/pzk5v/download?format=pdf)

**Gerard Chung**, David Ansong, & Gina Chowa. **Effects of Parenting Practices, Goals, and Style on Ghanaian Youth Financial Behavior**.

# 2023

Glatz, T., Lippold, M. A., **Gerard Chung**, Jensen, T **A Systematic Review of Parental Self-efficacy Among Parents of School-Age Children and Adolescents**. *Adolescent Research Review*, [[Article]](https://doi.org/10.1007/s40894-023-00216-w)

# 2022

Lauren A Eaves, Paul Lanier, Adam E Enggasser, **Gerard Chung**, Toby Turla, Julia E Rager, Rebecca C Fry (2022). **Generation of the Chemical and Social Stressors Integration Technique (CASS-IT) to Identify Areas of Holistic Public Health Concern: An Application to North Carolina**. *Science of The Total Environment*, [\[Preprint\]](http://dx.doi.org/10.2139/ssrn.4161726) [\[Article\]](https://www.sciencedirect.com/science/article/pii/S0048969722075118)

**Gerard Chung**, Xi Wen Chan, Paul Lanier, Peace Wong. **Associations Between Work-Family Balance, Parenting Stress, and Marital Conflicts During COVID-19 Pandemic in Singapore**. *Journal of Child and Family Studies*, Early View [\[Preprint\]](https://osf.io/nz9s8/download) [\[Article\]](https://doi.org/10.1007/s10826-022-02490-z)

**Gerard Chung**, Aloysius Chan, Lim Wei Loong (2022). **Systematic Reviews: A Research Guide for Social Service Professionals.** Social Service Research Centre. [\[Article\]](files/ssr/A-Research-Guide-to-Doing-a-Systematic-Review.pdf) [\[SSR\]](https://fass.nus.edu.sg/ssr/wp-content/uploads/sites/8/2022/09/A-Research-Guide-to-Doing-a-Systematic-Review.pdf)

**Gerard Chung**, Maria Rodriguez, Paul Lanier, Daniel Gibbs (2022). **Text-Mining Open-Ended Survey Responses Using Structural Topic Modeling: A Practical Demonstration to Understand Parents' Coping Methods During the COVID-19 Pandemic in Singapore**. *Journal of Technology in Human Services*. [\[Article\]](https://doi.org/10.1080/15228835.2022.2036301) [\[Preprint\]](https://osf.io/enzst/)

Karen Lee Yih Chee, **Gerard Chung** (2022). **The Design and Development of Interventions: An Application to an After-school Program by CampusImpact for Disadvantaged Families in Singapore.** *Snippet***,** *2***,** Social Service Research Centre. \[[Article](https://fass.nus.edu.sg/ssr/wp-content/uploads/sites/8/2022/06/Snippet-June_Issue-2_2022_LogicModelAfterSchoolCare_ResearchMentoringAbstracts-1-2.pdf)\] \[[ResearchGate](https://www.researchgate.net/publication/362845110_The_Design_and_Development_of_Interventions_An_Application_to_an_After-school_Program_by_CampusImpact_for_Disadvantaged_Families_in_Singapore)\]

**Gerard Chung**, Paul Lanier, Ding-Geng Chen (2022). **What predicts mothers' use of spanking in the first 6 years of early childhood? A latent growth curve analysis** *Child & Family Social Work*, *27*(2), 1356-7500. [\[Article\]](https://doi.org/10.1111/cfs.12866)

Paul Lanier, **Gerard Chung**, Roderick Rose (2022). **A Quasi-Experimental Study of Intensive Alternative Family Treatment to Prevent Entry of Youth to Psychiatric Residential Treatment** *Child and Adolescent Social Work Journal*, *39*(3), 303-311. [\[Article\]](https://doi.org/10.1007/s10560-021-00758-9)

**Gerard Chung** (2022). **News Media Representations of Social Service Agencies in Singapore during COVID19 Pandemic -- A Corpus Linguistics Approach.** *Snippet***,** 1**,** Social Service Research Centre. [\[Website\]](https://gerardchung.github.io/ssanews/) [\[Github\]](https://github.com/gerardchung/ssa_covid_news) \[[Article](https://fass.nus.edu.sg/ssr/wp-content/uploads/sites/8/2022/03/Snippet_Issue-1_2022_MinorityStress_CommunityConnectedness_NewsMedia_SocialServices.pdf)\] [\[ResearchGate\]](https://www.researchgate.net/publication/359207447_News_Media_Representations_of_Social_Service_Agencies_SSAs_in_Singapore_during_COVID-19_Pandemic_Social_Service_Research_Centre)[\[Preprint\]](https://osf.io/jy87c/)

Paul Lanier, Whitney Afonso, **Gerard Chung**, Katherine Bryant, Danny Ellis, Alexandria Coffey, Anita Brown-Graham, Sarah Verbiest (2022). **Demographic, Economic, and Geographic Factors Associated with Uptake of the Earned Income Tax Credit**. *Journal of Policy Practice and Research*.[\[Article\]](https://doi.org/10.1007/s42972-022-00054-5) [\[NCimpact\]](https://ncimpact.sog.unc.edu/wp-content/uploads/sites/1111/2022/04/Lanier-EITC-2022.pdf)

**Gerard Chung**, Kirsten Kainz, Sarah Rabiner Eisensmith, Paul Lanier (2022). **Effects of Youth Educational Aspirations on Academic Outcomes and Racial Differences: A Propensity Score Matching Approach**. *Journal of Child and Family Studies*. [\[Article\]](https://doi.org/10.1007/s10826-022-02227-y)

# 2021

**Gerard Chung**, Todd M Jensen, Anna Parisi, Rebecca J Macy, Paul Lanier (2021). **Impact of intimate partner violence on parenting and children's externalizing behaviors: transactional processes over time** *Violence against women*, *27*(14), 2576-2599. [\[Article\]](https://doi.org/10.1177/1077801220985125)

**Gerard Chung**, Ansong David, Kanisha Brevard, Ding-Geng Chen (2021). **Identifying treatment moderators of a trauma-informed parenting intervention with children in foster care: Using model-based recursive partitioning**. *Child Abuse & Neglect*, *117*. [\[Article\]](https://doi.org/10.1016/j.chiabu.2021.105065) [\[Preprint\]](https://osf.io/aqxer/)

Roderick A Rose, **Gerard Chung**, Paul J Lanier (2021). **Effectiveness of Intensive Alternative Family Treatment on Reducing Re-Admissions to Psychiatric Residential Treatment Facilities**. *Journal of Emotional and Behavioral Disorders*, *29*(2), 113-124. [\[Article\]](https://doi-org.libproxy1.nus.edu.sg/10.1177/1063426620980700)

# 2020

**Gerard Chung**, Quinton Smith, Joseph Frey, Paul Lanier (2020). **Associations Between Depression and the Parenting of Fathers in Head Start and Parental Self-efficacy as a Protective Factor**. *Children and Youth Services Review*, *120*. [\[Article\]](https://doi.org/10.1016/j.childyouth.2020.105758) <br>

Paul Lanier, Todd Jensen, Katherine Bryant, **Gerard Chung**, Roderick Rose, Quinton Smith, Lisa Lackmann (2020). **A systematic review of the effectiveness of children's behavioral health interventions in psychiatric residential treatment facilities**. *Children and Youth Services Review*, *113*. [\[Article\]](https://doi.org/10.1016/j.childyouth.2020.104951) <br>

**Gerard Chung**, Jonathan Phillips, Todd M Jensen, Paul Lanier (2020). **Parental involvement and adolescents' academic achievement: Latent profiles of mother and father warmth as a moderating influence**. *Family process*, *59*(2), 772-788. [\[Article\]](https://doi-org.libproxy1.nus.edu.sg/10.1111/famp.12450) <br>

**Gerard Chung**, Paul Lanier, Peace Wong (2020). **Mediating Effects of Parental Stress on Harsh Parenting And Parent-child Relationship During Coronavirus (COVID-19) Pandemic in Singapore.**. *Journal of Family Violence*, *37*, 801-812. [\[Article\]](https://doi.org/10.1007/s10896-020-00200-1) [\[Preprint\]](https://osf.io/vnf4j/) <br>

# 2019

Paul Lanier, Joseph Frey, Quinton Smith, **Gerard Chung** (2019). **A Quasi-Experimental Study of a Peer Support Group to Enhance Protective Factors for Fathers of Children in Head Start**. *Journal of Child and Family Studies*, *28*(6). [\[Article\]](https://doi.org/10.1007/s10826-019-01383-y)

Marcus YL Chiu, Corinne Ghoh, **Gerard Chung**, Kwok P Choi (2019). **Multistressed families in Singapore: A focus on transnational families**. *Children and Youth Services Review*, *101*(8). [\[Article\]](https://doi.org/10.1016/j.childyouth.2019.04.014)

# 
