---
title: "Talks"
---

Feel free to use my content. Drop me an email to say thanks or you could buy me a coffee [here](https://www.buymeacoffee.com/gerardchung)

# Talks/Presentations

-   **Associations of parenting stress with parenting and child adjustment outcomes during pandemic: A meta-analysis.** CIFA regional symposium and MSF Asian Family Conference. November 2022. \[[Slides](https://app.slidebean.com/p/v8zfyzj9tr/CIFAgerard-PUBLIC)\][\[File *14MB*\]](files/cifa/cifa_stress_gerard.pdf)

-   **Supporting Families During COVID-19: Text Analysis of Leaders' Messages from Social Service Agencies' Annual Reports.** CIFA regional symposium and MSF Asian Family Conference. November 2022. [[pdf]](files/cifa/gerard_poster_cifa.pdf)

-   **The Design and Development of Interventions: An Application to an After-school Program by CampusImpact for Disadvantaged Families in Singapore**. Lee Choon Guan Endowment Fund Public Lecture. 31st Aug 2022. Social Work Department, NUS. [\[File *20MB*\]](files/lgc_aug2022_for_lgcwebsite.pdf) [\[Slideshare\]](https://www.slideshare.net/GerardChung/lgcaug2022forlgcwebsitepdf)

-   **Analyzing textual data from open-ended survey questions**. Humanities and Social Sciences (HSS) and New Technologies Sandpit, NUS FASS Research Division. 15th Aug 2022. [\[File\]](files/hss_tech_sandpit_2022Aug.pdf) [\[Slideshare\]](https://www.slideshare.net/GerardChung/analyzing-textual-data-from-openended-survey-questions)

-   **Parenting and Coping During COVID-19 Circuit-Breaker in Singapore**. NUS Social Work Department. 8th August 2022. [\[html\]](https://app.slidebean.com/p/1zbif5ffl5/campusvisitseminar2022-FINAL) [\[pdf_24MB\]](files/job_talk_presentations/covidparentingtalk/covidparenting.pdf)

# Workshops

-   **Research Skills Workshop**. Research Mentoring Program. 1st Aug 2022. Social Service Research Centre, NUS. \[File soon!\]

-   **Quantitative Research & Data Analysis Workshop**. Research Mentoring Program. 2nd Aug 2022. Social Service Research Centre, NUS. \[File soon!\]

# Lectures

-   **Infant Development**. NUS Social Work LifeSpan Development. 9th Sept 2022.
    -   Physical Development [\[ppt\]](files/job_talk_presentations/1_infant_dev_physical_dev.pptx) [\[html\]](https://app.slidebean.com/p/rqnhrg1o81/Physical-Development-class-handout)
    -   Cognitive [\[ppt\]](files/job_talk_presentations/1_infant_dev_cognitive_dev.pptx) [\[html\]](https://app.slidebean.com/p/s9nedckjhu/Cognitive-FINAL-Class-Handouts)
    -   Socioemotional [\[ppt\]](files/job_talk_presentations/1_infant_dev_socioemo_dev.pptx) [\[html\]](https://app.slidebean.com/p/1zhl54xe8u/Socioemotional-Class-handouts)
